services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: english-sentences-nginx
    depends_on:
      - face
    volumes:
      - ./nginx/nginx.conf.server:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: sentences.explainit.ru,www.sentences.explainit.ru
      LETSENCRYPT_HOST: sentences.explainit.ru,www.sentences.explainit.ru

  face:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: npm run preview -- --host 0.0.0.0 --port 4173
    container_name: english-sentences-face
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    external:
      name: nginx-proxy
