services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: english-sentences-nginx
    depends_on:
      - face
    volumes:
      - ./nginx/nginx.conf.server:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: sentences.explainit.ru
      LETSENCRYPT_HOST: sentences.explainit.ru

  face:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    container_name: english-sentences-face
    command: npm run preview
    environment: {}

networks:
  default:
    external:
      name: nginx-proxy
