FROM node:22.2.0-alpine3.19

# Install wget for healthcheck
RUN apk add --no-cache wget

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Expose the port that the preview server will run on
EXPOSE 4173

# Set production environment
ENV NODE_ENV=production
