FROM node:22.2.0-alpine3.19 AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

# Serve the built app
FROM node:22.2.0-alpine3.19
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 4173
CMD ["npm", "run", "preview"]
